variables:
  # To optimize CI/CD time
  GIT_DEPTH: 10
  # To avoid SSL certificate verification error when cloning private repositories
  GIT_SSL_NO_VERIFY: 1

default:
  image:
    name: theohbrothers/docker-ansible:v2.10.7-alpine-3.13
    pull_policy: if-not-present
  tags:
    - docker

stages:
  - test

test:
  stage: test
  before_script:
    - mkdir -p ~/.ssh
    - cp -f "$SSH_PRIVATE_KEY" ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
    - rm -f ~/.ssh/known_hosts
    - mkdir -p /etc/ansible/
    - cp -f "$ANSIBLE_CFG" /etc/ansible/ansible.cfg
  script:
    - ansible-playbook -i $ANSIBLE_INVENTORY playbooks/main.yml
