variables:
  # To optimize CI/CD time
  GIT_DEPTH: 10
  # To avoid SSL certificate verification error when cloning private repositories
  GIT_SSL_NO_VERIFY: 1

default:
  image:
    name: theohbrothers/docker-ansible:v2.10.7-alpine-3.13
    pull_policy: if-not-present
  tags:
    - docker

stages:
  - CA
  - Server

.install_easyrsa:
  before_script:
    - apt update
    - apt install -y curl git
    - easyrsa_version=$(curl --silent "https://api.github.com/repos/OpenVPN/easy-rsa/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')

prepare-ca:
  extends: .install_easyrsa
  image: debian:11
  stage: CA
  script:
    - echo $easyrsa_version
  when: manual

prepare_server:
  extends: .install_easyrsa
  image: debian:11
  stage: Server
  script:
    - echo $easyrsa_version
  when: manual
# - ansible-playbook -i $ANSIBLE_INVENTORY --private-key "$SSH_PRIVATE_KEY" playbooks/main.yml
