version: '3'

services:
  attacker:
    build: ./attacker
    ports:
      - "8000:22"
    networks:
      pentest-network:
        ipv4_address: 10.1.1.1

networks:
  pentest-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.1/24