version: '3'

include:
  - "./bash/docker-compose.yml"
  - "./phpmyadmin/docker-compose.yml"

services:
  attacker:
    build: ./attacker
    container_name: attacker
    ports:
      - "2222:22"
    networks:
      - pentest-network


networks:
  pentest-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.1/24