# https://github.com/vulhub/vulhub/tree/master/phpmyadmin/CVE-2016-5734
version: '3'

services:
  cve-2016-5734:
    container_name: cve-2016-5734
    image: vulhub/phpmyadmin:4.4.15.6
    volumes:
      - ./cve-2016-5734/config.inc.php:/var/www/html/config.inc.php
    depends_on:
    - mysql-cve-2016-5734
    networks:
      - pentest-network

  cve-2018-12613:
    container_name: cve-2018-12613
    image: vulhub/phpmyadmin:4.8.1
    volumes:
      - ./cve-2018-12613/config.inc.php:/var/www/html/config.inc.php
    depends_on:
      - mysql-cve-2018-12613
    networks:
      - pentest-network

  mysql-cve-2016-5734:
    container_name: mysql-cve-2016-5734
    image: mysql:5.5
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    networks:
      - pentest-network
  mysql-cve-2018-12613:
    container_name: mysql-cve-2018-12613
    image: mysql:5.5
    environment: 
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    networks:
      - pentest-network