---
- hosts: backend
  become: true
  tasks:
    - name: Install packages
      apt:
        name: ["ca-certificates", "curl", "gnupg"]
        state: latest
        update_cache: true

    - name: Add Docker's official GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/trusted.gpg.d/docker.gpg
      args:
        creates: /etc/apt/trusted.gpg.d/docker.gpg

    - name: Get architecture
      command: dpkg --print-architecture
      register: architecture

    - name: Get version code name
      command: lsb_release -cs
      register: version

    - name: Add Docker apt repository
      apt_repository:
        # repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bullseye stable
        repo: deb [arch={{ architecture.stdout }} signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/debian {{ version.stdout }} stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
