---
# Configure and start the VPN server
- hosts: vpnserver
  roles:
    - vpnserver
    - caserver # This role can be removed if the certificates are copied from a different machine
  become: true
  tasks:
    - name: Copy server certificates and keys
      copy:
        src: "{{ item }}"
        dest: "{{ vpn_config_dir }}"
        owner: root
        group: root
        mode: 0600
        remote_src: true
      with_items:
        - "{{ easyrsa_dir }}/pki/ca.crt"
        - "{{ easyrsa_dir }}/pki/dh.pem"
        - "{{ easyrsa_dir }}/pki/issued/server.crt"
        - "{{ easyrsa_dir }}/pki/private/server.key"
        - "{{ easyrsa_dir }}/pki/ta.key"

    - name: Install packages
      apt:
        name: ["openvpn", "ufw"]
        state: latest
        update_cache: true

    - name: Configure openvpn server
      template:
        src: server.conf.j2
        dest: "{{ vpn_config_dir }}/server.conf"
        owner: root
        group: root
        mode: 0600

    - name: Allow IPv4 forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        reload: yes

    - name: Set the ufw forward policy to ACCEPT
      ufw:
        policy: allow
        direction: forward

    - name: Add ufw rule to allow openvpn udp traffic
      ufw:
        rule: allow
        port: 1194
        proto: udp

    - name: Add ufw rule to allow ssh traffic
      ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: Add ufw postrouting rule to masquerade client's traffic to the internal network with the VPN server's IP address
      ufw:
        rule: postrouting
        masquerade: yes
        interface: "{{ vpn_interface }}"

    - name: Add ufw rule to NAT traffic to the private network
      ufw:
        rule: nat
        src: "{{ vpn_network }}/{{ vpn_netcidr }}"
        dest: "{{ private_network }}/{{ private_netcidr }}"
        postrouting: yes

    # - name: Enable ufw
    #   ufw:
    #     state: enabled

    - name: Start openvpn server
      service:
        name: openvpn-server@server
        state: started
        enabled: true
