---
- hosts: backend
  become: true
  roles:
    - docker_installer
  tasks:
    - name: Copy pentest-lab directory
      copy:
        src: "pentest-lab"
        dest: "/root"
        owner: root
        group: root
        mode: 0755
        force: false

    # - name: Remove current "pentest-network" network
    #   command: "docker network rm pentest-network"
    #   ignore_errors: true

    - name: Run docker-compose
      command: "docker compose up -d"
      args:
        chdir: "/root/pentest-lab"
