- hosts: vpnserver
  roles:
    - caserver # This role can be removed if the certificates are copied from a different machine
  become: true
  tasks:
    - name: Generate client certificates
      command: "{{ easyrsa_bin }} build-client-full {{ item }} nopass"
      args:
        chdir: "{{ easyrsa_dir }}"
        creates: "{{ easyrsa_dir }}/pki/issued/{{ item }}.crt"
      loop: "{{ vpn_clients }}"

    # - name: Generate client config directories
    #   file:
    #     path: "{{ client_config_dir }}/{{ item }}"
    #     state: directory
    #     owner: root
    #     group: root
    #     mode: 0700
    #   loop: "{{ vpn_clients }}"

    # - name: Copy client certificates and keys
    #   copy:
    #     src: "{{ item }}"
    #     dest: "{{ client_config_dir }}/{{ item }}"
    #     owner: root
    #     group: root
    #     mode: 0600
    #     remote_src: true
    #   loop: "{{ vpn_clients }}"
    #   with_items:
    #     - "{{ easyrsa_dir }}/pki/ca.crt"
    #     - "{{ easyrsa_dir }}/pki/issued/{{ item }}.crt"
    #     - "{{ easyrsa_dir }}/pki/private/{{ item }}.key"
    #     - "{{ easyrsa_dir }}/pki/ta.key"

    # copy:
    #   src: "{{ item }}"
    #   dest: "{{ client_config_dir }}"
    #   owner: root
    #   group: root
    #   mode: 0600
    #   remote_src: true
    # with_items:
    #   - "{{ easyrsa_dir }}/pki/ca.crt"
    #   - "{{ easyrsa_dir }}/pki/issued/{{ item }}.crt"
    #   - "{{ easyrsa_dir }}/pki/private/{{ item }}.key"
    #   - "{{ easyrsa_dir }}/pki/ta.key"
