---
- hosts: vpnserver
  tasks:
    - name: Install dependencies
      become: true
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - openvpn
        - easy-rsa
        - ufw
