---
- hosts: vpnserver
  vars:
    easyrsa_path: "/usr/share/easy-rsa"
  tasks:
    - name: Install dependencies
      become: true
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - openvpn
        - easy-rsa
        - ufw

    - name: Initialize PKI
      command: "./easyrsa init-pki"
      args:
        chdir: "{{ easyrsa_path }}"
        creates: "{{ easyrsa_path }}/pki"

    - name: Build CA
      command: "./easyrsa build-ca nopass"
      args:
        chdir: "{{ easyrsa_path }}"
        creates: "{{ easyrsa_path }}/pki/ca.key"

    - name: Generate DH params
      command: "./easyrsa gen-dh"
      args:
        chdir: "{{ easyrsa_path }}"
        creates: "{{ easyrsa_path }}/pki/dh.pem"
