---
- hosts: vpnserver
  vars:
    easyrsa_install_path: "/opt/"
    easyrsa_bin: "{{ easyrsa_install_path }}/EasyRSA/easyrsa"
  tasks:
    - name: Install dependencies
      become: true
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - openvpn
        - ufw
        - curl

    - name: Install EasyRSA
      become: true
      shell: |
        easyrsa_version=$(curl --silent "https://api.github.com/repos/OpenVPN/easy-rsa/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
        easyrsa_url="https://github.com/OpenVPN/easy-rsa/releases/download/v${easyrsa_version}/EasyRSA-${easyrsa_version}.tgz"
        curl -so /tmp/easyrsa.tgz -L "$easyrsa_url"
        tar -xzf /tmp/easyrsa.tgz -C {{ easyrsa_install_path }}
        mv {{ easyrsa_install_path }}/EasyRSA-${easyrsa_version} {{ easyrsa_install_path }}/EasyRSA
      args:
        creates: "{{ easyrsa_bin }}"

    - name: Initialize PKI
      command: "{{ easyrsa_bin }} init-pki"
      args:
        creates: "{{ easyrsa_install_path }}/EasyRSA/pki"
# - name: Build CA
#   command: "{{ easyrsa_bin }} build-ca nopass"
#   args:
#     creates: "{{ easyrsa_install_path }}/EasyRSA/pki/ca.key"

# - name: Generate DH params
#   command: "./easyrsa gen-dh"
#   args:
#     chdir: "{{ easyrsa_install_path }}"
#     creates: "{{ easyrsa_install_path }}/pki/dh.pem"

# - name: Generate server certificate
